### ISSUE TITLE
图片不显示的问题

### ISSUE THREAD

**Issue by ZombiesYard** [hovenjay/MovieRecommendationSystem#1]
你好，我在自建服务器上运行了起来这个项目，然后就是图片没有显示请问一下是什么情况，只有当我自己点到图片url下载一次以后，再进入才会有图片

**Comment by hovenjay** [comment]
图片的 url 均来自豆瓣官方的图片链接，正常情况下图片加载是浏览器自动加载的，如果加载不顺利，有很多可能，我列举一二，你可以排查一下：

- 可能豆瓣官方的图片外链升级了或者加入了反爬反外链机制；
- 可能你的浏览器开启了省流量模式默认不主动加载图片或者浏览器版本不兼容；

**Comment by ZombiesYard** [comment]
你好，谢谢回复
我在head栏加入了<meta name="referrer" content="no-referrer" /&gt;
现在可以显示了





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Jason He"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月24日(星期一) 下午2:08
收件人:&nbsp;"hovenjay/MovieRecommendationSystem"<MovieRecommendationSystem@noreply.github.com&gt;;
抄送:&nbsp;"ZombiesYard"<1292364361@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [hovenjay/MovieRecommendationSystem] 图片不显示的问题 (#1)




图片的 url 均来自豆瓣官方的图片链接，正常情况下图片加载是浏览器自动加载的，如果加载不顺利，有很多可能，我列举一二，你可以排查一下：
  
可能豆瓣官方的图片外链升级了或者加入了反爬反外链机制；
 
可能你的浏览器开启了省流量模式默认不主动加载图片或者浏览器版本不兼容；
